### ISSUE TITLE
Adventure is still broken for 5.0.1

### ISSUE THREAD

**Issue by iiAhmedYT** [retrooper/packetevents#1500]
● **Describe the bug** 
  PacketEvents 2.12.1 throws ``NoClassDefFoundError``: ``net/kyori/adventure/util/Buildable$Builder`` when its update checker runs (and in any code path that loads GsonComponentSerializer$Builder). The bundled
  io.github.retrooper.packetevents.adventure.serializer.gson.GsonComponentSerializer$Builder interface still declares net.kyori.adventure.util.Buildable$Builder<...> as a superinterface, but that inner type was removed in Adventure 5.x (replaced by            
  net.kyori.adventure.builder.AbstractBuilder). The outer net.kyori.adventure.util.Buildable class still exists in Adventure 5.0.1, but the inner Builder interface does not, so any classloader resolution of GsonComponentSerializer$Builder fails when the
  runtime Adventure is 5.x.                                                                                                                                                                                                                                         
                       
  Verified with javap -v on packetevents-api-2.12.1.jar:
  public interface io.github.retrooper.packetevents.adventure.serializer.gson.GsonComponentSerializer$Builder
      extends net.kyori.adventure.builder.AbstractBuilder<...>,
              net.kyori.adventure.util.Buildable$Builder<...>,   // <-- missing in Adventure 5.x
              io.github.retrooper.packetevents.adventure.serializer.json.JSONComponentSerializer$Builder

  This is a binary incompatibility, not a relocation/shading issue — the same error reproduces whether PacketEvents is shaded or not, as long as the runtime Adventure is 5.x.

  ● **Software brand**
  Paper 1.21.11

  ● **Plugins**
  Only the plugin that bundles PacketEvents 2.12.1 alongside Adventure 5.0.1 needs to be present. No other plugins required to trigger it.

  Dependency set used in the failing build:
  - net.kyori:adventure-api:5.0.1
  - net.kyori:adventure-text-minimessage:5.0.1
  - net.kyori:adventure-text-serializer-gson:5.0.1
  - net.kyori:adventure-platform-bukkit:4.4.1
  - com.github.retrooper:packetevents-spigot:2.12.1

 ● **How To Reproduce**
  1. Create a plugin that depends on (or shades) packetevents-spigot:2.12.1 together with adventure-api:5.0.1 (and the matching text-serializer-gson:5.0.1).
  2. Initialize PacketEvents normally on plugin load (PacketEvents.getAPI().load() / init()), which kicks off the async update check.
  3. Start the server.
  4. Within a few seconds the packetevents-update-check-thread fails with the stack trace below.

  Reproduction does not require any client action — UpdateChecker.checkLatestReleasedVersion calls AdventureSerializer.gson(), which triggers loading of GsonComponentSerializer$Builder and immediately throws.

  ● **Expected behavior**
  PacketEvents 2.12.1 should be compatible with Adventure 5.x — its bundled adventure serializers should not declare net.kyori.adventure.util.Buildable$Builder as a superinterface, since that type no longer exists in Adventure 5.x. The AbstractBuilder
  superinterface alone is sufficient.

  ● **Additional context**
  Stack trace:
```
[13:42:15 WARN]: Exception in thread "packetevents-update-check-thread" java.lang.NoClassDefFoundError: to/itsme/itsmyconfig/shade/kyori/adventure/util/Buildable$Builder
[13:42:15 WARN]:        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
[13:42:15 WARN]:        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027)
[13:42:15 WARN]:        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
[13:42:15 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:263)
[13:42:15 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593)
[13:42:15 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:180)
[13:42:15 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:175)
[13:42:15 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
[13:42:15 WARN]:        at itsmyconfig-4.3.2 (3).jar//to.itsme.itsmyconfig.shade.packetevents.util.adventure.AdventureSerializer.gson(AdventureSerializer.java:227)
[13:42:15 WARN]:        at itsmyconfig-4.3.2 (3).jar//to.itsme.itsmyconfig.shade.packetevents.util.updatechecker.UpdateChecker.checkLatestReleasedVersion(UpdateChecker.java:55)
[13:42:15 WARN]:        at itsmyconfig-4.3.2 (3).jar//to.itsme.itsmyconfig.shade.packetevents.util.updatechecker.UpdateChecker.checkForUpdate(UpdateChecker.java:70)
[13:42:15 WARN]:        at itsmyconfig-4.3.2 (3).jar//to.itsme.itsmyconfig.shade.packetevents.util.updatechecker.UpdateChecker.lambda$handleUpdateCheck$1(UpdateChecker.java:126)
[13:42:15 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[13:42:15 WARN]: Caused by: java.lang.ClassNotFoundException: to.itsme.itsmyconfig.shade.kyori.adventure.util.Buildable$Builder
[13:42:15 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:208)
[13:42:15 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:175)
[13:42:15 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
[13:42:15 WARN]:        ... 13 more
```
  Adventure 5.0.1 jar contents (relevant subset):
  net/kyori/adventure/util/Buildable.class            ← present
  net/kyori/adventure/util/Buildable$Builder.class    ← REMOVED in 5.x
  net/kyori/adventure/builder/AbstractBuilder.class   ← new replacement

**Comment by TheFaser** [comment]
I don't have that problem, are you sure it's not your problem?

**Comment by TheFaser** [comment]
you need to relocate adventure for your plugin and for packetevents

**Comment by iiAhmedYT** [comment]
> you need to relocate adventure for your plugin and for packetevents

Of course I did relocate for both @-@ its exactly why its not working for me. Did you actually try test this scenario properly?

**Comment by TheFaser** [comment]
maybe because I use Libby to download PacketEvents (including transitive dependencies) hmm

**Comment by iiAhmedYT** [comment]
> maybe because I use Libby to download PacketEvents (including transitive dependencies) hmm

Then 4.x is possibly running on your server then

**Comment by TheFaser** [comment]
> Then 4.x is possibly running on your server then

no, because I had errors related to Adventure 5.x and PacketEvents

**Comment by TheFaser** [comment]
maybe something is loaded to classpath and works fine, I can't be sure

**Comment by iiAhmedYT** [comment]
> > Then 4.x is possibly running on your server then
> 
> no, because I had errors related to Adventure 5.x and PacketEvents

Did you test it with the GsonSerializer too?

**Comment by iiAhmedYT** [comment]
https://github.com/ItsMyStudio/ItsMyConfig is the project, might be helpful to look into it

**Comment by TheFaser** [comment]
> Did you test it with the GsonSerializer too?

Not specifically, because libby will download everything it needs anyway. I'll try to test it later, when I'm free, to check this case

**Comment by TheFaser** [comment]
@iiAhmedYT I checked this and made sure that the problem is not with Libby or how I download PacketEvents. It is an issue on your side. I tried calling `GsonComponentSerializer.builder().build()` in my code, importing it from PacketEvents, and I get a compilation error. 

<img width="887" height="115" alt="Image" src="https://github.com/user-attachments/assets/edff3834-9d6d-4953-92e3-3dd411f6feb9" />

This means I cannot perform this action. You most likely have an old version of Kyori in your project, which is why it allows you to build the project. That is why the error from your call appears on the server

**Comment by iiAhmedYT** [comment]
please check the project gradle, it has latest adventure version that i can assure you, otherwise this would have not happened

**Comment by TheFaser** [comment]
> please check the project gradle, it has latest adventure version that i can assure you, otherwise this would have not happened

you can't build project with this code because it doesn't have this

**Comment by TheFaser** [comment]
Perhaps IDEA allows you to build project because you are using `packetevents-spigot` and `implementation`, while I am using `compileOnly` and `packetevents-api`. Just remove that line of code with serializer because it will not work for you with Adventure 5.x. This is because PacketEvents itself has a dependency on Adventure 4.x

**Comment by iiAhmedYT** [comment]
> @iiAhmedYT I checked this and made sure that the problem is not with Libby or how I download PacketEvents. It is an issue on your side. I tried calling `GsonComponentSerializer.builder().build()` in my code, importing it from PacketEvents, and I get a compilation error. 
> 
> <img width="887" height="115" alt="Image" src="https://github.com/user-attachments/assets/edff3834-9d6d-4953-92e3-3dd411f6feb9" />
> 
> This means I cannot perform this action. You most likely have an old version of Kyori in your project, which is why it allows you to build the project. That is why the error from your call appears on the server

I re-read this now. I shadow and relocate PacketEvents insidevmy plugin. The error doesn't happen to me in compile-time because it's just a shaded-in jar. And that is a side-effect of having an older version of Kyori/Adventure


The serializer call is INSIDE of PacketEvents

**Comment by TheFaser** [comment]
> The serializer call is INSIDE of PacketEvents

yeah... I was able to replicate this problem

<img width="2426" height="970" alt="Image" src="https://github.com/user-attachments/assets/f3e1afb9-122d-4ce0-ac21-701027e978e0" />

**Comment by TheFaser** [comment]
in addition to this issue, I wrote in Discord that there is a problem with version 1.21.4 

<img width="1531" height="224" alt="Image" src="https://github.com/user-attachments/assets/104deb2a-2ea5-42b5-af55-197323fccd8b" />

https://mclo.gs/Q19zdaJ 

I think we should wait until booky has some free time and try to solve this problem. Alternatively, we can try to do a PR

**Comment by iiAhmedYT** [comment]
What's a good solution tho? Builder calls with reflections? Compile with 5.0?

**Comment by TheFaser** [comment]
Since PacketEvents doesn't relocate adventure yet, we need to use reflection to make older versions work
